---
clickhouse:
  hosts:
    clickhouse-01:
      ansible_host: "{{ lookup('env','CLICKHOUSE_IP') | ansible.utils.ipv4 }}"
      ansible_user: centos
vector:
  hosts:
    vector-01:
      ansible_host: "{{ lookup('env','VECTOR_IP') | ansible.utils.ipv4 }}"
      ansible_user: centos
lighthouse:
  hosts:
    lighthouse-01:
      ansible_host: "{{ lookup('env','LIGHTHOUSE_IP') | ansible.utils.ipv4 }}"
      ansible_user: centos