---
clickhouse_version: "22.3.3.44"
clickhouse_packages:
  - clickhouse-client
  - clickhouse-server
  - clickhouse-common-static
clickhouse_user: loger
clickhouse_password: loger
source_host: "{{ lookup('env','VECTOR_IP') }}"
